name: DAST ZAP Scan

on:
  workflow_dispatch:

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: DAST Zap Scan on Juice Shop

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run ZAP Full Scan
        id: zap
        uses: zaproxy/action-full-scan@v0.12.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          docker_name: 'ghcr.io/zaproxy/zaproxy:stable'
          target: 'https://juice-shop.herokuapp.com'
          cmd_options: '-a -z "-config connection.ssl_cert_validation=false"'
          allow_issue_writing: false

      - name: Upload ZAP Report Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: zap-dast-reports
          path: |
            report_html.html
            report_json.json
            zap.out
